set_property IOSTANDARD LVCMOS33 [get_ports a]
set_property IOSTANDARD LVCMOS33 [get_ports b]
set_property IOSTANDARD LVCMOS33 [get_ports cin]
set_property IOSTANDARD LVCMOS33 [get_ports cout]
set_property IOSTANDARD LVCMOS33 [get_ports s]
set_property PACKAGE_PIN V10 [get_ports a]

set_property PACKAGE_PIN U11 [get_ports b]
set_property PACKAGE_PIN U12 [get_ports cin]
set_property PACKAGE_PIN V11 [get_ports cout]
set_property PACKAGE_PIN V12 [get_ports s]
